service: ms-order
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'api'}
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:SendMessage
          Resource:
            Fn::GetAtt:
              - CKSOrderQueue
              - Arn
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "*"
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    ORDER_QUEUE_URL:
      Ref: CKSOrderQueue

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - node_modules/@aws-sdk/**
    - node_modules/**/@aws-sdk/**
    - '**/*.test.ts'
    - '**/*.spec.ts'

functions:
  createOrderProcessor:
    handler: src/adapters/driver/lambda/create_order_processor.handler
    memorySize: 128
    events:
      - http:
          path: /v1/order
          method: POST

  createOrder:
    handler: src/adapters/driver/lambda/create_order.handler
    memorySize: 128
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CKSOrderQueue
              - Arn
          batchSize: 1
          maximumRetryAttempts: 0

resources:
  Resources:
    CKSOrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CKSOrderQueue-${self:provider.stage}

plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: false
  esbuild:
    bundle: true
    minify: true
    target: node20
    exclude:
      - better-sqlite3
      - mysql2
      - mysql
      - sqlite3
      - tedious
      - pg-query-stream
      - oracledb